-- Diff code generated with pgModeler (PostgreSQL Database Modeler)
-- pgModeler version: 0.9.4
-- Diff date: 2025-05-06 00:45:06
-- Source model: samizdat
-- Database: samizdat
-- PostgreSQL version: 13.0

-- [ Diff summary ]
-- Dropped objects: 0
-- Created objects: 2
-- Changed objects: 0

SET search_path=public,pg_catalog,account;
-- ddl-end --


-- [ Created objects ] --
-- object: account.emailconfirmationrequests | type: TABLE --
-- DROP TABLE IF EXISTS account.emailconfirmationrequests CASCADE;
CREATE TABLE account.emailconfirmationrequests (
	requestid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	newemail character varying NOT NULL,
	ip inet,
	requesttime timestamp with time zone NOT NULL DEFAULT now(),
	contacts_contactid bigint NOT NULL,
	confirmationuuid uuid NOT NULL DEFAULT gen_random_uuid(),
	CONSTRAINT emailconfirmationrequests_pk PRIMARY KEY (requestid)
);
-- ddl-end --
ALTER TABLE account.emailconfirmationrequests OWNER TO samizdat;
-- ddl-end --



-- [ Created foreign keys ] --
-- object: contacts_fk | type: CONSTRAINT --
-- ALTER TABLE account.emailconfirmationrequests DROP CONSTRAINT IF EXISTS contacts_fk CASCADE;
ALTER TABLE account.emailconfirmationrequests ADD CONSTRAINT contacts_fk FOREIGN KEY (contacts_contactid)
REFERENCES account.contacts (contactid) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

