-- Diff code generated with pgModeler (PostgreSQL Database Modeler)
-- pgModeler version: 0.9.4
-- Diff date: 2024-05-23 21:52:52
-- Source model: samizdat
-- Database: samizdat
-- PostgreSQL version: 13.0

-- [ Diff summary ]
-- Dropped objects: 0
-- Created objects: 5
-- Changed objects: 0

SET search_path = public,pg_catalog,poll;
-- ddl-end --


-- [ Created objects ] --
-- object: poll | type: SCHEMA --
-- DROP SCHEMA IF EXISTS poll CASCADE;
CREATE SCHEMA poll;
-- ddl-end --
ALTER SCHEMA poll OWNER TO samizdat;
-- ddl-end --

-- object: poll.signers | type: TABLE --
-- DROP TABLE IF EXISTS poll.signers CASCADE;
CREATE TABLE poll.signers
(
  signerid  BIGINT                   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  firstname VARCHAR(191)             NOT NULL,
  lastname  VARCHAR(191)             NOT NULL,
  email     VARCHAR(191)             NOT NULL,
  pc        VARCHAR(15),
  city      VARCHAR(191)             NOT NULL,
  cc        VARCHAR(4)               NOT NULL,
  ip        inet                     NOT NULL,
  submitted TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  confirmed TIMESTAMP WITH TIME ZONE,
  uuid      uuid                     NOT NULL,
  logotype  SMALLINT                 NOT NULL DEFAULT 0,
  language  VARCHAR(8)               NOT NULL DEFAULT 'en',
  reviewed  SMALLINT                 NOT NULL DEFAULT 0,
  pollid    INTEGER                  NOT NULL,
  CONSTRAINT signers_pk PRIMARY KEY (signerid),
  CONSTRAINT uuid_uq UNIQUE (uuid)
);
-- ddl-end --
COMMENT ON COLUMN poll.signers.pc IS E'Postal code';
-- ddl-end --
COMMENT ON COLUMN poll.signers.cc IS E'Country code';
-- ddl-end --
ALTER TABLE poll.signers
  OWNER TO samizdat;
-- ddl-end --

-- object: poll.polls | type: TABLE --
-- DROP TABLE IF EXISTS poll.polls CASCADE;
CREATE TABLE poll.polls
(
  pollid      INTEGER                  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  title       VARCHAR(191)             NOT NULL,
  description TEXT,
  tail        SMALLINT                 NOT NULL DEFAULT 10,
  count       INTEGER                  NOT NULL DEFAULT 0,
  active      BOOLEAN                  NOT NULL DEFAULT TRUE,
  CONSTRAINT polls_pk PRIMARY KEY (pollid)
);
-- ddl-end --
ALTER TABLE poll.polls
  OWNER TO samizdat;
-- ddl-end --

-- object: signers_pollid_idx | type: INDEX --
-- DROP INDEX IF EXISTS poll.signers_pollid_idx CASCADE;
CREATE INDEX signers_pollid_idx ON poll.signers
  USING btree
  (
   pollid
    );
-- ddl-end --


-- [ Created foreign keys ] --
-- object: polls_fk | type: CONSTRAINT --
-- ALTER TABLE poll.signers DROP CONSTRAINT IF EXISTS polls_fk CASCADE;
ALTER TABLE poll.signers
  ADD CONSTRAINT polls_fk FOREIGN KEY (pollid)
    REFERENCES poll.polls (pollid) MATCH SIMPLE
    ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --


INSERT INTO poll.polls(pollid, title)
VALUES
  (1, 'Sample poll');
