-- Diff code generated with pgModeler (PostgreSQL Database Modeler)
-- pgModeler version: 0.9.4
-- Diff date: 2025-05-05 16:02:31
-- Source model: samizdat
-- Database: samizdat
-- PostgreSQL version: 13.0

-- [ Diff summary ]
-- Dropped objects: 0
-- Created objects: 2
-- Changed objects: 0

SET search_path=public,pg_catalog,web;
-- ddl-end --


-- [ Created objects ] --
-- object: web.homes | type: TABLE --
-- DROP TABLE IF EXISTS web.homes CASCADE;
CREATE TABLE web.homes (
	homeid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	homedir character varying NOT NULL DEFAULT gen_random_uuid(),
	users_userid bigint NOT NULL,
	CONSTRAINT homes_pk PRIMARY KEY (homeid),
	CONSTRAINT homedir_uq UNIQUE (homedir)
);
-- ddl-end --
ALTER TABLE web.homes OWNER TO samizdat;
-- ddl-end --



-- [ Created foreign keys ] --
-- object: users_fk | type: CONSTRAINT --
-- ALTER TABLE web.homes DROP CONSTRAINT IF EXISTS users_fk CASCADE;
ALTER TABLE web.homes ADD CONSTRAINT users_fk FOREIGN KEY (users_userid)
REFERENCES account.users (userid) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

