meta:
  name:
    description: Samizdat is a content management platform to create content on a stick, currently aimed at the war in Ukraine.
    keywords: Ukraine,Russia,censorship,invasion,CMS
  property:
