import 'suneditor/dist/css/suneditor.min.css'
import suneditor from 'suneditor'
// import im from 'suneditor/src/plugins/dialog/link'
import list from 'suneditor/src/plugins/submenu/list'
import {video, link, image, table, blockquote} from 'suneditor/src/plugins'
import lang from 'suneditor/src/lang'
import {sv} from 'suneditor/src/lang'