-- Diff code generated with pgModeler (PostgreSQL Database Modeler)
-- pgModeler version: 1.1.0-beta1
-- Diff date: 2025-05-12 18:20:38
-- Source model: samizdat
-- Database: samizdat
-- PostgreSQL version: 16.0

-- [ Diff summary ]
-- Created objects: 20
-- Changed objects: 0

SET search_path=public,pg_catalog,account,web,poll,article,customer,stats;
-- ddl-end --

ALTER TABLE poll.polls DROP COLUMN IF EXISTS title CASCADE;
-- ddl-end --
ALTER TABLE poll.polls DROP COLUMN IF EXISTS description CASCADE;
-- ddl-end --
ALTER TABLE web.homes DROP COLUMN IF EXISTS users_userid CASCADE;
-- ddl-end --
ALTER TABLE account.emailconfirmationrequests DROP COLUMN IF EXISTS contacts_contactid CASCADE;
-- ddl-end --


-- [ Created objects ] --
-- object: stats | type: SCHEMA --
-- DROP SCHEMA IF EXISTS stats CASCADE;
CREATE SCHEMA stats;
-- ddl-end --
ALTER SCHEMA stats OWNER TO samizdat;
-- ddl-end --

-- object: public."position" | type: TYPE --
-- DROP TYPE IF EXISTS public."position" CASCADE;
CREATE TYPE public."position" AS
ENUM ('current','next','previous');
-- ddl-end --
ALTER TYPE public."position" OWNER TO samizdat;
-- ddl-end --

-- object: stats.counters | type: TABLE --
-- DROP TABLE IF EXISTS stats.counters CASCADE;
CREATE TABLE stats.counters (
	counterid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	CONSTRAINT counters_pk PRIMARY KEY (counterid)
);
-- ddl-end --
ALTER TABLE stats.counters OWNER TO samizdat;
-- ddl-end --

-- object: stats.referrers | type: TABLE --
-- DROP TABLE IF EXISTS stats.referrers CASCADE;
CREATE TABLE stats.referrers (
	referrerid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	CONSTRAINT referrers_pk PRIMARY KEY (referrerid)
);
-- ddl-end --
ALTER TABLE stats.referrers OWNER TO samizdat;
-- ddl-end --

-- object: stats.visitcaches | type: TABLE --
-- DROP TABLE IF EXISTS stats.visitcaches CASCADE;
CREATE TABLE stats.visitcaches (
	visitcacheid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	CONSTRAINT visitcaches_pk PRIMARY KEY (visitcacheid)
);
-- ddl-end --
ALTER TABLE stats.visitcaches OWNER TO samizdat;
-- ddl-end --

-- object: customer.servicestypes | type: TABLE --
-- DROP TABLE IF EXISTS customer.servicestypes CASCADE;
CREATE TABLE customer.servicestypes (
	servicestypeid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	CONSTRAINT servicestypes_pk PRIMARY KEY (servicestypeid)
);
-- ddl-end --
ALTER TABLE customer.servicestypes OWNER TO samizdat;
-- ddl-end --

-- object: customer.servicetypenames | type: TABLE --
-- DROP TABLE IF EXISTS customer.servicetypenames CASCADE;
CREATE TABLE customer.servicetypenames (
	servicetypenameid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	languageid integer NOT NULL,
	servicetypeid integer NOT NULL,
	servicetypename varchar(191) NOT NULL,
	CONSTRAINT servicetypenames_pk PRIMARY KEY (servicetypenameid)
);
-- ddl-end --
ALTER TABLE customer.servicetypenames OWNER TO samizdat;
-- ddl-end --

-- object: customer.services | type: TABLE --
-- DROP TABLE IF EXISTS customer.services CASCADE;
CREATE TABLE customer.services (
	serviceid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	customerid bigint NOT NULL,
	servicetypeid integer NOT NULL,
	webserviceid bigint,
	datausage integer NOT NULL DEFAULT 0,
	CONSTRAINT services_pk PRIMARY KEY (serviceid)
);
-- ddl-end --
ALTER TABLE customer.services OWNER TO samizdat;
-- ddl-end --

-- object: poll.polltranslations | type: TABLE --
-- DROP TABLE IF EXISTS poll.polltranslations CASCADE;
CREATE TABLE poll.polltranslations (
	polltranslationid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	languageid integer NOT NULL,
	pollid bigint NOT NULL,
	title varchar(191) NOT NULL,
	description text,
	version integer NOT NULL DEFAULT 1,
	CONSTRAINT polltranslations_pk PRIMARY KEY (polltranslationid)
);
-- ddl-end --
ALTER TABLE poll.polltranslations OWNER TO samizdat;
-- ddl-end --

-- object: contactid | type: COLUMN --
-- ALTER TABLE account.emailconfirmationrequests DROP COLUMN IF EXISTS contactid CASCADE;
ALTER TABLE account.emailconfirmationrequests ADD COLUMN contactid bigint NOT NULL;
-- ddl-end --


-- object: userid | type: COLUMN --
-- ALTER TABLE account.emailconfirmationrequests DROP COLUMN IF EXISTS userid CASCADE;
ALTER TABLE account.emailconfirmationrequests ADD COLUMN userid bigint NOT NULL;
-- ddl-end --


-- object: userid | type: COLUMN --
-- ALTER TABLE web.homes DROP COLUMN IF EXISTS userid CASCADE;
ALTER TABLE web.homes ADD COLUMN userid bigint NOT NULL;
-- ddl-end --




-- [ Created foreign keys ] --
-- object: languages_fk | type: CONSTRAINT --
-- ALTER TABLE customer.servicetypenames DROP CONSTRAINT IF EXISTS languages_fk CASCADE;
ALTER TABLE customer.servicetypenames ADD CONSTRAINT languages_fk FOREIGN KEY (languageid)
REFERENCES public.languages (languageid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
-- ddl-end --

-- object: servicetypes_fk | type: CONSTRAINT --
-- ALTER TABLE customer.servicetypenames DROP CONSTRAINT IF EXISTS servicetypes_fk CASCADE;
ALTER TABLE customer.servicetypenames ADD CONSTRAINT servicetypes_fk FOREIGN KEY (servicetypeid)
REFERENCES customer.servicestypes (servicestypeid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

-- object: customers_fk | type: CONSTRAINT --
-- ALTER TABLE customer.services DROP CONSTRAINT IF EXISTS customers_fk CASCADE;
ALTER TABLE customer.services ADD CONSTRAINT customers_fk FOREIGN KEY (customerid)
REFERENCES customer.customers (customerid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

-- object: servicetypes_fk | type: CONSTRAINT --
-- ALTER TABLE customer.services DROP CONSTRAINT IF EXISTS servicetypes_fk CASCADE;
ALTER TABLE customer.services ADD CONSTRAINT servicetypes_fk FOREIGN KEY (servicetypeid)
REFERENCES customer.servicestypes (servicestypeid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

-- object: webservices_fk | type: CONSTRAINT --
-- ALTER TABLE customer.services DROP CONSTRAINT IF EXISTS webservices_fk CASCADE;
ALTER TABLE customer.services ADD CONSTRAINT webservices_fk FOREIGN KEY (webserviceid)
REFERENCES web.webservices (webserviceid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
-- ddl-end --

-- object: languages_fk | type: CONSTRAINT --
-- ALTER TABLE poll.polltranslations DROP CONSTRAINT IF EXISTS languages_fk CASCADE;
ALTER TABLE poll.polltranslations ADD CONSTRAINT languages_fk FOREIGN KEY (languageid)
REFERENCES public.languages (languageid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

-- object: polls_fk | type: CONSTRAINT --
-- ALTER TABLE poll.polltranslations DROP CONSTRAINT IF EXISTS polls_fk CASCADE;
ALTER TABLE poll.polltranslations ADD CONSTRAINT polls_fk FOREIGN KEY (pollid)
REFERENCES poll.polls (pollid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

-- object: users_fk | type: CONSTRAINT --
-- ALTER TABLE account.emailconfirmationrequests DROP CONSTRAINT IF EXISTS users_fk CASCADE;
ALTER TABLE account.emailconfirmationrequests ADD CONSTRAINT users_fk FOREIGN KEY (userid)
REFERENCES account.users (userid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

