-- Diff code generated with pgModeler (PostgreSQL Database Modeler)
-- pgModeler version: 0.9.4
-- Diff date: 2024-05-23 22:21:25
-- Source model: samizdat
-- Database: samizdat
-- PostgreSQL version: 13.0

-- [ Diff summary ]
-- Dropped objects: 0
-- Created objects: 11
-- Changed objects: 0

SET search_path = public,pg_catalog,article;
-- ddl-end --


-- [ Created objects ] --
-- object: article | type: SCHEMA --
-- DROP SCHEMA IF EXISTS article CASCADE;
CREATE SCHEMA article;
-- ddl-end --
ALTER SCHEMA article OWNER TO samizdat;
-- ddl-end --

-- object: article.articles | type: TABLE --
-- DROP TABLE IF EXISTS article.articles CASCADE;
CREATE TABLE article.articles
(
  articleid BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  CONSTRAINT articles_pk PRIMARY KEY (articleid)
);
-- ddl-end --
ALTER TABLE article.articles
  OWNER TO samizdat;
-- ddl-end --

-- object: article.articlenames | type: TABLE --
-- DROP TABLE IF EXISTS article.articlenames CASCADE;
CREATE TABLE article.articlenames
(
  articlenameid BIGINT       NOT NULL GENERATED ALWAYS AS IDENTITY,
  articleid     BIGINT,
  languageid    BIGINT DEFAULT 1,
  articlename   VARCHAR(191) NOT NULL,
  CONSTRAINT articlenames_pk PRIMARY KEY (articlenameid)
);
-- ddl-end --
ALTER TABLE article.articlenames
  OWNER TO samizdat;
-- ddl-end --

-- object: article.articleprices | type: TABLE --
-- DROP TABLE IF EXISTS article.articleprices CASCADE;
CREATE TABLE article.articleprices
(
  articlepriceid BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  articleid      BIGINT,
  currencyid     INTEGER,
  price          DECIMAL,
  CONSTRAINT articleprices_pk PRIMARY KEY (articlepriceid)
);
-- ddl-end --
ALTER TABLE article.articleprices
  OWNER TO samizdat;
-- ddl-end --

-- object: article.articlevatrates | type: TABLE --
-- DROP TABLE IF EXISTS article.articlevatrates CASCADE;
CREATE TABLE article.articlevatrates
(
  articlevatrateid INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  vatrateid        INTEGER,
  articleid        BIGINT,
  CONSTRAINT articlevatrates_pk PRIMARY KEY (articlevatrateid)
);
-- ddl-end --
ALTER TABLE article.articlevatrates
  OWNER TO samizdat;
-- ddl-end --


-- [ Created foreign keys ] --
-- object: articles_fk | type: CONSTRAINT --
-- ALTER TABLE article.articlenames DROP CONSTRAINT IF EXISTS articles_fk CASCADE;
ALTER TABLE article.articlenames
  ADD CONSTRAINT articles_fk FOREIGN KEY (articlenameid)
    REFERENCES article.articles (articleid) MATCH SIMPLE
    ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: languages_fk | type: CONSTRAINT --
-- ALTER TABLE article.articlenames DROP CONSTRAINT IF EXISTS languages_fk CASCADE;
ALTER TABLE article.articlenames
  ADD CONSTRAINT languages_fk FOREIGN KEY (articlenameid)
    REFERENCES public.languages (languageid) MATCH SIMPLE
    ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: articles_fd | type: CONSTRAINT --
-- ALTER TABLE article.articleprices DROP CONSTRAINT IF EXISTS articles_fd CASCADE;
ALTER TABLE article.articleprices
  ADD CONSTRAINT articles_fd FOREIGN KEY (articleid)
    REFERENCES article.articles (articleid) MATCH SIMPLE
    ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

-- object: currencies_fk | type: CONSTRAINT --
-- ALTER TABLE article.articleprices DROP CONSTRAINT IF EXISTS currencies_fk CASCADE;
ALTER TABLE article.articleprices
  ADD CONSTRAINT currencies_fk FOREIGN KEY (currencyid)
    REFERENCES public.currencies (currencyid) MATCH SIMPLE
    ON DELETE SET NULL ON UPDATE NO ACTION;
-- ddl-end --

-- object: vatrates_fk | type: CONSTRAINT --
-- ALTER TABLE article.articlevatrates DROP CONSTRAINT IF EXISTS vatrates_fk CASCADE;
ALTER TABLE article.articlevatrates
  ADD CONSTRAINT vatrates_fk FOREIGN KEY (vatrateid)
    REFERENCES public.vatrates (vatrateid) MATCH SIMPLE
    ON DELETE SET NULL ON UPDATE NO ACTION;
-- ddl-end --

-- object: articles_fk | type: CONSTRAINT --
-- ALTER TABLE article.articlevatrates DROP CONSTRAINT IF EXISTS articles_fk CASCADE;
ALTER TABLE article.articlevatrates
  ADD CONSTRAINT articles_fk FOREIGN KEY (articleid)
    REFERENCES article.articles (articleid) MATCH SIMPLE
    ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

