meta:
  name:
    description: Everything about fake news. Samizdat is a content management platform with ability to keep content on a USB stick
    keywords: censorship,CMS,fake news,samizdat,publishing,artificial intelligence,open source