-- Diff code generated with pgModeler (PostgreSQL Database Modeler)
-- pgModeler version: 1.1.0-beta1
-- Diff date: 2025-09-13 17:08:20
-- Source model: samizdat
-- Database: samizdat
-- PostgreSQL version: 16.0

-- [ Diff summary ]
-- Dropped objects: 1
-- Created objects: 4
-- Changed objects: 0

SET search_path=public,pg_catalog,web,account;
-- ddl-end --


-- [ Dropped objects ] --
ALTER TABLE web.resources DROP CONSTRAINT IF EXISTS parent_fk CASCADE;
-- ddl-end --
ALTER TABLE web.resources DROP COLUMN IF EXISTS parentid CASCADE;
-- ddl-end --


-- [ Created objects ] --
-- object: web.resourceconnections | type: TABLE --
-- DROP TABLE IF EXISTS web.resourceconnections CASCADE;
CREATE TABLE web.resourceconnections (
	resourceconnectionid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	parent bigint NOT NULL,
	child bigint NOT NULL

);
-- ddl-end --
ALTER TABLE web.resourceconnections OWNER TO samizdat;
-- ddl-end --



-- [ Created constraints ] --
-- object: src_lang_uq | type: CONSTRAINT --
-- ALTER TABLE web.resources DROP CONSTRAINT IF EXISTS src_lang_uq CASCADE;
ALTER TABLE web.resources ADD CONSTRAINT src_lang_uq UNIQUE (src,languageid);
-- ddl-end --



-- [ Created foreign keys ] --
-- object: parent_fk | type: CONSTRAINT --
-- ALTER TABLE web.resourceconnections DROP CONSTRAINT IF EXISTS parent_fk CASCADE;
ALTER TABLE web.resourceconnections ADD CONSTRAINT parent_fk FOREIGN KEY (parent)
REFERENCES web.resources (resourceid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

-- object: child_fk | type: CONSTRAINT --
-- ALTER TABLE web.resourceconnections DROP CONSTRAINT IF EXISTS child_fk CASCADE;
ALTER TABLE web.resourceconnections ADD CONSTRAINT child_fk FOREIGN KEY (child)
REFERENCES web.resources (resourceid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

